import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {default: "Eats Picker", template: "%s | Eats Picker"},
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          {/* Load the Google Maps JavaScript API script with your API key */}
          <script
            src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyAv4k61NzGM_zRuYgfI0QJH8R-6fWr7R9Y&libraries=places`}
            async
            defer
          ></script>
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
